### ISSUE TITLE
Instance is Destroyed on Stop

### ISSUE THREAD

**Issue by dotun** [neo4j-contrib/ec2neo#13]
Hi,

Great work making it easy to deploy Neo4j on AWS.

I noticed that stopping a deployed instance using the provided template erases directory content in /var/lib/neo4j. This renders the instance un-usable.

My guess is that the installation is done on ephemeral storage with the default instance type of m3.medium, which loses data on stop. Is any other instance type immune to this? Can you move the installation to non-ephemeral storage?

Thanks.

Dotun.

**Comment by simpsonjulian** [comment]
Hey @dotun 

What's your use case for stopping the instance?   The current design is to use instance storage and enjoy decent disk latency.  Backups go to EBS.

We could mount the EBS volume on and make Neo4j run on that, but that brings other complications.

Anyway, tell me how you plan to use it and we'll have a think.

**Comment by dotun** [comment]
Hi @simpsonjulian,

After deploying, I tried to assign an SSL certificate to the neo4j instance to enable HTTPS. I needed to restart after changing the neo4j-server.properties file, so I tried the "service" restart as well as the "neo4j-server" restart, but both commands ended with a message like "neo4j may not have started".

So, I decided to restart the entire EC2 instance; that's when I discovered this behaviour.

Regards,
Dotun.

**Comment by simpsonjulian** [comment]
So if `service neo4j-service restart` didn't help, then I think there was a configuration issue (or something) that stopped Neo4j from starting.  Restarting the instance wouldn't have helped in this case.  Have a look in `/var/log/neo4j` to start with ..

**Comment by dotun** [comment]
Hi,

In addition to my earlier reason for restarting my EC2 instance, I just received a notification from AWS about maintenance work they have to do on a different instance of mine, which will require them to restart it when they are done. 

So, I believe ec2neo template should allow for restarts.

Regards,
Dotun.

**Comment by simpsonjulian** [comment]
Hi @dotun 

Good points, let me think about those ...

Julian.

**Comment by simpsonjulian** [comment]
Hey @dotun 

I don't think it was our intention to provide a CloudFormation template that would manage the entire lifecycle of a Neo4j install.  Sorry if we gave that impression.  I've updated the README to make that clearer.

I'm open to pull requests to make this a bit more robust.  If you're looking for something that's going to take all of the admin work out of things, I'd suggest that you use one of our [hosting partners](http://neo4j.com/developer/guide-cloud-deployment/) as they'll take care of the entire lifecycle.

Julian.

**Comment by jbrozena22** [comment]
To confirm - the answer was your instance will be blown away if Amazon does any maintenance and we should instead use a different hosting partner?

If that's the case, this feels like a very incomplete solution.

**Comment by simpsonjulian** [comment]
Hey @jbrozena22 

There's three options here that address your (valid) concern about AWS resources not being durable:

* We change this CloudFormation template to allow the user to run their app on an EBS filesystem (perhaps moving backups to S3)
* You choose another approach, like other people's Puppet, Chef and Ansible templates to deploy Neo4j in HA mode on multiple AWS machines
* You move to Amazon ECS and Docker, where (IIRC) people are successfully deploying Neo4j in an HA configuration.

I suggested to OP that he might look at hosting with one of our partners for convenience.  Suggest you open another issue if you want to continue this conversation.
