### ISSUE TITLE
create web server and upload neo from local

### ISSUE THREAD

**Issue by gg4u** [neo4j-contrib/ec2neo#15]
Hello,
this is not an issue, but questions.

which is the procedure to upload the neo4j db from local into the cloud?
is it sufficient to copy the folder into the /neo4j folder created in EBS ?

Also, any procedure to set up a web server into AWS ?
I'd like to create a webserver, using flask / neo4j-phyton, but don't know how to ...
is there maybe a guide helping to figure it out?
in which folder should I upload it ?
how to create it?

thank you!

**Comment by simpsonjulian** [comment]
Hi @gg4u 

To upload neo4j: you should:
*  stop your local database
* make a tarball of the _graph.db_ folder
* upload it to the server using SCP
* stop neo4j on the server
* locate the remote _graph.db_ folder
* rename it
* overwrite it from your tarball
* start neo4j

You're probably best to deploy your flask app to Heroku, and configure it to talk to your database.  I've spent quite some time getting gunicorn and nginx to play nicely.

**Comment by gg4u** [comment]
Hi @simpsonjulian thank you, I will try that.

**Comment by simpsonjulian** [comment]
No worries @gg4u!
