### ISSUE TITLE
Is an elastic IP required?

### ISSUE THREAD

**Issue by mtrahan** [neo4j-contrib/ec2neo#19]
Does neo4j need an elastic IP to work?  I tried searching the docs but didn't see anything obvious.  Thanks!

**Comment by simpsonjulian** [comment]
Hey @mtrahan 

Neo4j doesn't care about Elastic IP's.  By default it listens on localhost only so as not to unwittingly expose itself to the Internet.  That should be overcome with the CF stack though.

What can you observe?

**Comment by mtrahan** [comment]
Thanks for the quick response!  That is what I thought.  I didn't get a chance to try it out yet since elastic IPs are kind of hard to come by so I wanted to verify they weren't needed.  I will remove that portion of the template and give it a try.  Thanks again.

**Comment by simpsonjulian** [comment]
No problem.  Let us know how you get on.
