### ISSUE TITLE
Deployment gets rolled back

### ISSUE THREAD

**Issue by ghost** [neo4j-contrib/ec2neo#8]
Hi, apologies in advance for newbie question.

When I run this script in CloudFormation for the Ubuntu version, the EC2 server deployment gets rolled back with:

  The following resource(s) failed to create: [Server]. . Rollback requested by user.
  12:20:42 UTC-0500 CREATE_FAILED   AWS::EC2::Instance  Server  API: ec2:RunInstances Not authorized for images: [ami-1a059572]

I'm not clear whether this is because I need to set up some kind of permissions, or whether there is an issue with the AMI. I've tried searching for this AMI, but I cannot find it on the EC2 AMI search.

Any help is appreciated.

**Comment by tritonresearch** [comment]
Thank you!
